### ISSUE TITLE
Adding Pagination

### ISSUE THREAD

**Issue by crackjack** [etianen/django-watson#100]
As per the wiki, it has been stated that paginate_by followed by an integer is to be used for pagination.

But, I can't find a place where I could use that. Can you please show me a reference of whether it is a global thing, or I need to do it for every model?

Regards.

**Comment by etianen** [comment]
When you include the watson urls, add a kwargs={"paginate_by"=20} to the url().

Something like:

url("^search/", include("watson.urls"), kwargs={})

**Comment by crackjack** [comment]
Thank you.

You may want to replace the "equal_to" by "colon" in kwargs={"paginate_by": 20}
