### ISSUE TITLE
I don't understand the installation guid.

### ISSUE THREAD

**Issue by ghost** [etianen/django-watson#103]
Hi, sorry but I can't really understand how it works, I'm a beginner and here is how I have done it.
I installed the app in my settings and added the url in url.py
I added nothing in my views, couldn't know what to put in there, I want the search form in my index.
If someone could troubleshoot my problem it would be really helpfull, thanks.

![a](https://cloud.githubusercontent.com/assets/7415299/6887962/ff967762-d66e-11e4-8600-8794a27ce584.png)
![b](https://cloud.githubusercontent.com/assets/7415299/6903073/24f9d0b8-d718-11e4-9e2d-ac85612c5b30.png)

**Comment by etianen** [comment]
If you’ve added the url to urls.py, then you just need to add a search form to your index HTML file.

Example here: https://github.com/etianen/django-watson/wiki/Built-in-views

**Comment by Huriddin** [comment]
I did, but the thing is the app can not find the words in my title. I was maybe be wondering if there is an error in my views ?
![3](https://cloud.githubusercontent.com/assets/7415299/6901213/201870a6-d70c-11e4-9010-aa0662ea9f43.png)

**Comment by etianen** [comment]
Can you give me an example of a title and a search that doesn’t find the title.

Try using the python API from the command line to debug whether your search is working:

https://github.com/etianen/django-watson/wiki/Searching-models

**Comment by Huriddin** [comment]
sure. 
![c](https://cloud.githubusercontent.com/assets/7415299/6915999/0d56ef00-d799-11e4-95d9-841626d6ebba.png)
