### ISSUE TITLE
Django 1.8/9 compatibility

### ISSUE THREAD

**Issue by puterleat** [etianen/django-watson#106]
The following errors/warnings appear when using django 1.8:

    /watson/models.py:27: RemovedInDjango19Warning: Model class watson.models.SearchEntry doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.

    /watson/registration.py:21: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9. from django.utils.importlib import import_module

**Comment by stripathi669** [comment]
+1 on this

**Comment by etianen** [comment]
I'll take a pull request to fix this, and merge right away. Otherwise, I'll look into it myself when my schedule eases up.

Should be easy pickings for someone, though!
