### ISSUE TITLE
Trouble with install

### ISSUE THREAD

**Issue by dkotenok** [etianen/django-watson#113]
Hi.
I have tried to install package and failed. 
Here's why:

![Image]
(https://www.evernote.com/shard/s49/sh/2ef4507a-b096-4396-b3f1-caa35589fe97/fd554716d9bcd173/res/a515afb5-4b18-4476-a38b-f1ce53e64ffa/skitch.png?resizeSmall&width=832)

Do you have any ideas about what is going on?
Thank you very much!

**Comment by carltongibson** [comment]
Looks like you need 'django.contrib.contenttypes' in your `INSTALLED_APPS`

**Comment by dkotenok** [comment]
@carltongibson, thank you!

**Comment by carltongibson** [comment]
@dkotenok You're welcome :-)
