### ISSUE TITLE
Search weighting documentation unclear

### ISSUE THREAD

**Issue by radeksvarz** [etianen/django-watson#115]
hi,

search weighting code example is unclear: https://github.com/etianen/django-watson/wiki/Registering-models#tweaking-search-weighting

What declares the high / medium / low priority?

It looks like it is the order of methods in the class.

Can you please clarify?

**Comment by etianen** [comment]
Look closer! The docstrings of the functions say that get_title has high priority, get_description has medium, and get_content has low.

**Comment by radeksvarz** [comment]
So the priority is given just by the method name?

This is unclear from the doc. 

Its also strange for the cases, where you do not have your initial model with title, description and content attributes.

I assume the example with concrete model would clarify that.

**Comment by etianen** [comment]
How is it unclear? Under the method name is a piece of text describing the priority. SearchAdapter is an abstract base class that you can implement as you wish.

I agree that some models don’t fit nicely into those categories. However, calling the methods get_high_priority_search_text, get_medium_priority_search_text and get_low_priority_search_text would be more verbose, and in the default search templates get_title is used as the title, and get_description is used for a description. So it kinda does make sense.

**Comment by radeksvarz** [comment]
My apologies if I made any tension. I am quite new to django-watson.
Now I understand. Still I believe the concrete example with model Person and Pet would make the doc clear on the first sight.

Something that shows that the name of Pet has higher priority then the owner.
