### ISSUE TITLE
howto - ngrams?

### ISSUE THREAD

**Issue by radeksvarz** [etianen/django-watson#116]
Hi,

I am comparing django-watson to Whoosh. How do you use ngrams with watson?

http://whoosh.readthedocs.org/en/latest/ngrams.html?highlight=ngram

**Comment by etianen** [comment]
django-watson doesn’t use ngrams specifically. It’s a compatibility shim on top of database full text search, so the implementation depends on the database backend used.

In the case of postgres, for example, the full text engine provides language-based word stemming and stop word removal, beyond which some sort of very clever index is involved.

**Comment by radeksvarz** [comment]
So, how do you propagate the ngram configiration down to the DB level when using watson?

**Comment by etianen** [comment]
There is no ngram configuration to propagate. The database full text search is used however it is configured in the database config file.
