### ISSUE TITLE
Non latin language support

### ISSUE THREAD

**Issue by bee-keeper** [etianen/django-watson#122]
Hi,

I wrote the following test which passes with sqlite and fails with Postgres 9.4.4.  The `testSearchWithAccent` test passes with both db's

```
def testSearchWithNonLatinLanguage(self):
        WatsonTestModel1.objects.create(
            title = "title model1 instance12",
            content = "content model1 instance13 ایران",
            description = "description model1 instance13",
        )
        self.assertEqual(watson.search("ایران").count(), 1)
```

In short, I'm wondering if this text should be expected to pass?  I'm asking as I have inherited a project using Watson and despite the search working on a server with Postgres 9.1, it returns no results locally with 9.4.  I see Postgres doesn't have a Farsi dictionary/stemmer and in the case of the working instance Watson is using `to_tsquery('pg_catalog.english'`.

Thanks in advance,

**Comment by etianen** [comment]
Are you using the master branch? It may contain the fix you're looking
for...

**Comment by bee-keeper** [comment]
Hi,

Thanks for the quick response.  Yes, I cloned master.  Clearly there is something wrong (probably related to the failing test I reported).  So to clarify, are you saying the above test should be expected to pass?  Should I PR the test above?

**Comment by etianen** [comment]
I'm not sure if the test is expected to pass. django-watson relies on
postgres' own full text search engine, which won't always get things right.

As it happens, postgres versions earlier than 9.3 don't support prefix
matching, and django-watson detects this and only performs whole-word
matching for older postgres servers. It's possible that this is leading to
the test passing on 9.1, and failing on 9.4.

Try adding the following to your settings file:

WATSON_BACKEND = "watson.backends.PostgresLegacySearchBackend"

See if that helps. If it does, then it'll be to do with the prefix matching.

**Comment by bee-keeper** [comment]
Hi, yep changing the backend didn't help.  I think i need to do a some forensics and come back with more info.  The issue is clearly with Postgres as the query executed is exactly the same.  I set up a test env with 9.1 and actually I can't get the test to pass there either so my theory about versions is incorrect.  I suspect there must be some postgres config issue which is causing the problem.

**Comment by bee-keeper** [comment]
Ok, so changing the backend to the legacy search does fix the issue when using Postgres on Ubuntu.  When using Postgres 9.4.4 on OSX it has no effect and non latin full text search simply returns no results.  Thanks for the headsup re the backend.
