### ISSUE TITLE
Duplicate results 

### ISSUE THREAD

**Issue by Boogymanx** [etianen/django-watson#127]
Hey there :) 

I'm using watson for search (duh) but I'm having an issue where, when I search on different fields, the same instance of a Model gets returned. I have a form that takes four parameters (keyword, function, sector and region). Region can be entered as a digit or a string (the string can be either a city or a province). You can see the form here https://dpaste.de/5YyH . The issue I'm having is that my form will return the same model instance as a SearchEntry, even though I thought my check would make sure it didn't - I'm guessing because I'm searching on a different field, I should get different SearchEntry objects.  

http://imgur.com/pxP4zQI shows the print statements and http://imgur.com/xslcQ1E the live output. The parameters I'm entering should return only one database entry, but because I'm searching on multiple fields it returns more often. I've tried writing my if statements differently, but I get either an error because of flawed code or the same results. Is there a built-in way to check for duplicates or am I just not seeing a simple solution? 

Many thanks in advance for reading and replying,
Boogy

**Comment by etianen** [comment]
Just add .distinct() to the end of the search queryset to de-duplicate.
It's just a normal Django queryset!

**Comment by Boogymanx** [comment]
Thanks for the quick reply! That fixed it indeed - I also noticed that I
had registered models that shouldn't have been searchable by themselves,
only as FK on an other model which was an other issue I was having. Great
job on Watson by the way, it's awesome :)

**Comment by etianen** [comment]
Glad it's working now! :D
