### ISSUE TITLE
CharField vs TextField for models

### ISSUE THREAD

**Issue by Fitblip** [etianen/django-watson#128]
Hey there!

I tried to store some large fields (inadvertently) and noticed I was getting some errors updating the watson models. Specifically `value too long for type character varying(1000)` which is to be expected since they are CharFields, and I'm trying to write something larger than 1000 chars into the index. 

Have you looked into the possibility of converting those to TextFields? I assume you wanted to keep them CharFields for performance reasons, but I wanted to get your take on if the move to a TextField was reasonable/feasible. 

I also wanted to see what you think the best way to truncate may be if you think CharFields should be kept for perf reasons. 

I absolutely *love* watson, huge thanks for all your hard work on it :). 

 Cheers!

**Comment by etianen** [comment]
Hmm, that's odd. The only field with a length restriction is the title
field of the SearchEntry model, the others are already text fields with no
length limit.

By default, the only thing stored in the title field is the __unicode__ /
__str__ representation of your model. Limiting your __unicode__ / __str__
result to 1000 characters seems sensible.

Of course, watson should probably truncate the title field anyway, rather
than allowing it to error...

**Comment by Fitblip** [comment]
That's fair, the issue was exposed while doing some resilience testing on our platform, and I wanted to both raise it to your attention and get a bead on your recommendation for re-mediation. 

Silently truncating probably makes the most sense here, so I've opened a PR with what I think is the right fix. 

Thanks for the speedy response, and again for all the work you've done with Watson! :)
