### ISSUE TITLE
Automaticlly update indexes for manytomany fields

### ISSUE THREAD

**Issue by davegri** [etianen/django-watson#131]
I have the following configuration:

     class CrawlersConfig(AppConfig):
         name = "crawlers"
         def ready(self):
             Image = self.get_model("Image")
             watson.register(Image,  fields=('tags__name',), store=('thumbnail__url', 'page_url', 'source_url',          'get_origin_display', 'tags__name'))     
   

According to the docs I just need to add the watson middleware in order for a change in the manytomany fields to update the index. I added it but it still doesn't update when I add or remove tags to my images.

**Comment by etianen** [comment]
I've just pushed up a commit to master that should fix this.

**Comment by davegri** [comment]
It's still not working, also it dosen't create a new index for new objects, is it supposed to?
how do I automatically index every new object I add?

**Comment by etianen** [comment]
I assume that you've set the app config as the default app config for your
app?

**Comment by davegri** [comment]
I think so, can you elaborate?

**Comment by etianen** [comment]
In the __init__.py of the app, you need something along the lines of:

DEFAULT_APP_CONFIG = "yourapp.apps.YourAppConfig"

Easy check, put a print("foo") in your ready() method to ensure its
executed!

**Comment by davegri** [comment]
Yeah, the models wouldn't be registered otherwise so I have that.

**Comment by etianen** [comment]
If your models are registered, then calling save() on the model will create
a new SearchEntry in the database. The change I pushed ot master was also
adding to the SearchEntry index when the M2M fields are changed.

If that's not happening, then I don't think your models are being
registered. Some print("foo") around the registration code will verify if
this is the case,
