### ISSUE TITLE
TypeError: <object> is not JSON serializable 

### ISSUE THREAD

**Issue by dimmg** [etianen/django-watson#132]
Hi, suppose I have the following class

```
class Post(models.Model):
    image = models.ImageField(upload_to='some_path', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
```

I want to add `image` and `created_at` as metadata, like `watson.register(Post, store=('image', 'created_at'))`. However when I'm doing this it is saying that both types are not JSON serializable.
Is this django-watson specific, or should I somehow manually handle the serialization? 
Thanks!

**Comment by etianen** [comment]
So, only primitive types are JSON serializable by default. This is a
limitation of JSON.

However, you can create a custom search adapter and override serialize_meta
and deserialize_meta, to provide custom serialization and deserialization.
You can see their signatures here:

https://github.com/etianen/django-watson/blob/master/src/watson/registration.py#L155

This feature is only present in the master branch, so you'll have to update
your watson installation. It's a new feature, so let me know how you get on!

**Comment by dimmg** [comment]
Thank you, I was able to get the desired output by creating a custom search adapter as you've suggested.
```
import datetime
import json
from django.db.models.fields.files import ImageFieldFile
from django.core.serializers.json import DjangoJSONEncoder
from watson.registration import SearchAdapter


class CustomSearchAdapter(SearchAdapter):

    def serialize_meta(self, obj):
        meta_obj = super(CustomSearchAdapter, self).get_meta(obj)
        for key in meta_obj:           
            if isinstance(meta_obj[key], ImageFieldFile):
                meta_obj[key] = meta_obj[key].path
            elif isinstance(meta_obj[key], datetime.date):
                meta_obj[key] = meta_obj[key].strftime('%d %B %Y')
                
        return json.dumps(meta_obj, cls=DjangoJSONEncoder)

```
Then passing explicitly the adapter when registering the model.
```
    def ready(self):
        Post = self.get_model('Post')
        watson.register(Post, adapter_cls=CustomSearchAdapter, store=('created_at', 'image',))
```
