### ISSUE TITLE
What about icontains search?

### ISSUE THREAD

**Issue by mkmich** [etianen/django-watson#133]
When I have a model for user registered on www, an email address is the main title. The most usefull search is something like '@domain.com'. But it returns nothing. Did you think about "icontains" option?

**Comment by etianen** [comment]
Unfortunately, django-watson is limited by the capabilities of the database
full text search backends which only support word prefix matching.

**Comment by manuganji** [comment]
Exactly. This is a pretty big surprise for me. Even jquery datatable supports this. I have assumed that this would be obviously supported.

**Comment by etianen** [comment]
I just had someone complain that it supported prefix matching at all. They
just wanted whole-word matching. Funny world.
