### ISSUE TITLE
Filter method creates a postgres query with a postfix wildcard

### ISSUE THREAD

**Issue by davegri** [etianen/django-watson#134]
I'm pretty much a novice when it comes to full-text search so this might be a misunderstanding or possibly I've set something up wrong but should a search for "cat" return results that contain "cathedral"? or for example "bee" returns results that contain "beer" ? this is how I've got everything set up:

Models:

    class Tag(models.Model):
        name = models.CharField(max_length=100)
    
        def __str__(self):
            return self.name
    
    class Image(models.Model):
    
        source_url = models.URLField(max_length=400)
        page_url = models.URLField(unique=True, max_length=400)
        thumbnail = models.ImageField(upload_to='thumbs', null=True)
        origin = models.CharField(choices=origins, max_length=2)
        tags = models.ManyToManyField(Tag)
        hash = models.CharField(max_length=576)
        hidden = models.BooleanField(default=False)
    
        def __str__(self):
            return ', '.join([tag.name for tag in self.tags.all()])

Registration:

    from django.apps import AppConfig
    import watson
    
    class CrawlersConfig(AppConfig):
        name = "crawlers"
        def ready(self):
            Image = self.get_model("Image")
            watson.register(Image,  fields=('tags__name',), store=('thumbnail__url', 'page_url', 'source_url', 'get_origin_display', 'tags__name'))

A search for "cat" returns results that not only contain but rank a result with this list of tags higher:
window, up, stone, statue, painting, old, light, indoor, curve, carving, building, Roman art, Church organ, church bust, CC0, **catholic wealth**, **Catholic church**, Miscellaneous, angels, sculptures, ceiling, **catholic**, religious, golden, gold, **cathedral**, religion, church

than this list of tags:
**cat face**, **portrait of cat**, **cats**, animals, **cat**

Here is an example for the DB query being created:

    SELECT DISTINCT (ts_rank_cd(watson_searchentry.search_tsv, to_tsquery('pg_catalog.english', '$$cat$$:*'))) AS "watson_rank", "crawlers_image"."id", "crawlers_image"."source_url", "crawlers_image"."page_url", "crawlers_image"."thumbnail", "crawlers_image"."origin", "crawlers_image"."hash", "crawlers_image"."hidden" FROM "crawlers_image" , "watson_searchentry" WHERE (NOT ("crawlers_image"."hidden" = true) AND NOT ("crawlers_image"."id" IN (SELECT U0."id" AS Col1 FROM "crawlers_image" U0 LEFT OUTER JOIN "crawlers_image_tags" U1 ON ( U0."id" = U1."image_id" ) WHERE U1."tag_id" IS NULL)) AND "crawlers_image"."id" <= 37374 AND (watson_searchentry.engine_slug = 'default') AND (watson_searchentry.search_tsv @@ to_tsquery('pg_catalog.english', '$$cat$$:*')) AND (watson_searchentry.object_id_int = "crawlers_image"."id") AND (watson_searchentry.content_type_id = 7)) ORDER BY "watson_rank" DESC LIMIT 20

the important part:
`AND (watson_searchentry.search_tsv @@ to_tsquery('pg_catalog.english', '$$cat$$:*'))`

why `'$$cat$$:*'` and not `'$$cat$$'`?

can this behavior be changed?

**Comment by etianen** [comment]
The search is backed by the database's full text search functionality. For
Postgres, it's pretty good, for MySQL, it's fairly good, and for SQLite
it's pretty non-existent.

The search is based on prefix matching of stemmed words. So a search for
"person" will also match "personable".

**Comment by davegri** [comment]
Ok i get that, but why is a search for 'cat' returning 'cathedral' and a search for 'bees' returning 'beer'? I'm using PostgreSQL and running the following query returns the correct results:
`SELECT content FROM watson_searchentry WHERE title @@ to_tsquery('english', '$$bee$$');`

but using the django-watson filter method adds a postfix wildcard like this:
`SELECT content FROM watson_searchentry WHERE title @@ to_tsquery('english', '$$bee$$:*');`

this returns irrelevant results like beer or beetles

why is this the default behavior and can it be changed?

**Comment by etianen** [comment]
This is the default behaviour because it's often the desired behaviour. You
can change it with the following setting:

WATSON_BACKEND = "watson.backends.PostgresLegacySearchBackend"

**Comment by davegri** [comment]
Thats weird, one would assume that in searching for "bees" a result containing beer would be completely irrelevant in 99% of cases. thanks for the fix anyhow.

**Comment by etianen** [comment]
I dunno, I'd like a search for "brew" to find "brewery", or maybe a search
for "alcohol" to find "alcoholic".

Most people complain that django-watson doesn't support suffix and
within-word matching too. Can't please everyone.

**Comment by davegri** [comment]
Doesn't PostgreSQL full-text-search stemming automatically turn brew and brewery, and alcohol and alcoholic into the same word anyway ?

**Comment by etianen** [comment]
Nope!

```
dave=# select to_tsvector('brewery');
 to_tsvector 
-------------
 'breweri':1
(1 row)

dave=# select to_tsvector('brew');
 to_tsvector 
-------------
 'brew':1
(1 row)
```
