### ISSUE TITLE
Application AppConfig???

### ISSUE THREAD

**Issue by alzearafat** [etianen/django-watson#135]
Hi,

I am a new kid on django/python and your application, so please bear with me :)
I'm trying to understand this part of your doc : 

------------------------------------------------------------------------------
![alt text](http://i66.tinypic.com/2dbqq2p.png "Logo Title Text 1")
------------------------------------------------------------------------------

I don't know where exactly I should put these piece of code? In its own file (something like appconfig.py)? Or in other existing files?

Any enlightenment would be greatly appreciated.

Please excuse my English, 
Thanks in advance :)

**Comment by etianen** [comment]
The official docs are here: https://docs.djangoproject.com/en/1.8/ref/applications/#configuring-applications

I've updated the wiki to include this link for future confused people! :)

**Comment by alzearafat** [comment]
Hi @etianen , thank you!  :D
