### ISSUE TITLE
[SOLVED] Search give zero result

### ISSUE THREAD

**Issue by alzearafat** [etianen/django-watson#137]
Hi,

I have a problem using django-watson (I'm using built-in views). The search result is always none, eventhough the input is correct and the data is exsist. This is the output of buildwatson command : 

```
Deleted 0 stale search entry(s) in u'default' search engine.
Deleted 0 stale search entry(s) in u'admin' search engine.
Refreshed 0 search entry(s) in u'admin' search engine.
```

Please have a look of my codes : 

**models.py**
```
class Post(models.Model):
	author = models.ForeignKey(User, related_name="user_posts", null=True, blank=True)
	title = models.CharField(max_length=200)
        ...

	def __str__(self):
		return str(self.title)
```

**apps.py**
```
from django.apps import AppConfig
import watson

class JourneyAppConfig(AppConfig):
    name = "journey"
    def ready(self):
        post = self.get_model("post")
        watson.register(post)
```

*The app name is "Journey"*

I did not change any views. My DB is Postgre, Django 1.8.5.

Please help,
Thanks in advance

**Comment by etianen** [comment]
Did you set it as the default app config?

https://docs.djangoproject.com/en/1.8/ref/applications/#configuring-applications

**Comment by alzearafat** [comment]
Hi,

Sorry, my mistake, forgot to set app config in __init__.py :D 
Thank you very much for mentioning it,

Solved.

**Comment by etianen** [comment]
No worries. :)
