### ISSUE TITLE
Django 1.8.5 - Application names aren't unique

### ISSUE THREAD

**Issue by dmart914** [etianen/django-watson#138]
Hello,

I'm attempting to register models on Django 1.8.5. Here's the basics:

Project root: AdTracker/
App: AdTracker/WebInterface

AdTracker/WebInterface/apps.js:

    from django.apps import AppConfig
    import watson
    
    class WebInterfaceWatsonConfig(AppConfig):
        name = 'WebInterface'
        label = 'wi.WebIntWat'
        def ready(self):
            AssignmentWatson = self.get_model("Assignment")
            BusinessWatson = self.get_model("Business")
            FileWatson = self.get_model("File")
    
            watson.register(AssignmentWatson)
            watson.register(BusinessWatson)
            watson.register(FileWatson)
    

Here's my output after I run python3 manage.py buildwatson:

    ubuntu@[host]:~/AdTracker$ python3 manage.py buildwatson
    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 325, in execute
        django.setup()
      File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 101, in populate
        "duplicates: %s" % ", ".join(duplicates))
    django.core.exceptions.ImproperlyConfigured: Application names aren't unique, duplicates: WebInterface
    ubuntu@[host]:~/AdTracker$

If this is something I can help fix, I'd love to contribute. I just need a little direction; I've never contributed to an open-source project before.

**Comment by luzfcb** [comment]
@dmart914 

the error message says there is more than one "WebInterface" in your INSTALLED_APPS.
remove duplicate items.

**Comment by dmart914** [comment]
Hi, @luzfcb. Thanks for the help.

Here's what my INSTALLED_APPS looks like:

    INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'WebInterface',
        'crispy_forms',
        'crispy_forms_foundation',
        'watson',
        'WebInterface.apps.WebInterfaceWatsonConfig',
    )

The Django documentation on Applications led me to believe that I had to add the Config class to my INSTALLED_APPS listings. Is this not accurate? When I comment the WebInterfaceWatsonConfig line out, I get the following output:

    ubuntu@[host]:~/AdTracker$ python3 manage.py buildwatson
    Deleted 0 stale search entry(s) in 'default' search engine.
    Deleted 0 stale search entry(s) in 'admin' search engine.
    Refreshed 0 search entry(s) in 'admin' search engine.

I figured there would be a 'WebInterface' entry in the output. Should I not expect that?


Thanks!

**Comment by etianen** [comment]
You either add the app package, or a dotted path to the app config, not
both.

The output of buildwatson doesn't list the names of apps. Instead, those
"search engines" represent standalone full text indices - one for the
admin, one for the public site.
