### ISSUE TITLE
Cannot disable ranking

### ISSUE THREAD

**Issue by jasonguy** [etianen/django-watson#151]
Having a couple issues I think are database related. I have watson working great with a basic linux/mysql setup, however, the production site is percona (supposed to be mysql too). Anyhow, I was seeing the search return results for 'blah'. Then tried some other searches that may or may not work. Tried to search for 'blah' again, and it didn't return any results. CLI seems to work fine every time. Not sure what the problem is, but I figured simplifying the SQL query is a good thing to do.

Anyhow, while troubleshooting, I thought I should disable the ranking stuff because it is not really necessary for my setup, since I order the result table separately. The documentation shows how to do this by passing it into watson.search(). But I don't see an easy way to pass this setting upon registration, or the URL include statement: include("watson.urls", namespace="watson"), {'ranking' : False}),

What's the proper way to adjust this setting?

**Comment by etianen** [comment]
There's no way to adjust that via the generic views. I'd take a pull
request to add the feature, but it's not otherwise a priority.

I'm not sure why the CLI would give different results to the generic views.
My understanding is that they use exactly the same lookup API.
