### ISSUE TITLE
Model.objects.create doesn't trigger index update

### ISSUE THREAD

**Issue by Alphare** [etianen/django-watson#152]
Maybe I'm doing something wrong, but when I save my model using the save() method instead, the index is updated.
I thought create() was just a wrapper for save()? 
I know that bulk operations don't work, but this is for a single instance.

**Comment by etianen** [comment]
I'm pretty sure that Model.objects.create triggers the Django post_save
signal, which should update the index.

Are you sure that .create isn't updating the index? A minimal test case
would be useful here.

**Comment by Alphare** [comment]
Looking at the `watson_searchentry` database, it seems a new entry is added, but when using `watson.search` it does not appear, at least not immediately. But now, when I try a manual save, nothing changes. Is there some sort of timer?

**Comment by etianen** [comment]
There's no timer. It should appear immediately.

Can I have a look at your Watson registration code? And the mode you are
searching?

**Comment by Alphare** [comment]
I think I figured it out. If I create/update entries directly in PyCharm's database view, it doesn't go through Django's database management system... or through watson. I'm dumb!
Sorry for wasting your time, thanks for the fast replies.

**Comment by etianen** [comment]
No worries! Glad you found the solution!
