### ISSUE TITLE
Doc tweak: 'module' object is not callable

### ISSUE THREAD

**Issue by shacker** [etianen/django-watson#156]
In the Getting Started [doc](https://github.com/etianen/django-watson/wiki) it says:

`search_results = watson.search("Your search text")`

but that results in:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: 'module' object is not callable
```

by reading the source code I was able to figure out that I needed to do this first:

`from watson import search as watson`

So that should be added to the guide.

**Comment by etianen** [comment]
Apologies, I'd included that import earlier in the wiki page, so assumed it was implicit in the usage. I guess not.

I've included the import line at the top of every example.

Also relevant here: #157
