### ISSUE TITLE
Searching on URLs

### ISSUE THREAD

**Issue by jeffes** [etianen/django-watson#159]
I'm trying to figure out how to break up URLs so the individual components can be searched on individually. eg: http://www.cnn.com/test/big_news

I'd like that URL (and the content around it) to be matched on a search for "big_news".

The best I've seemed to find is this: http://stackoverflow.com/questions/14093230/word-separators-for-postgres-full-text-search-with-rails

Unfortunately my SQL-fu doesn't seem to be good enough right now to cajole this into working with Watson (taking into account different naming etc). I have it working in a standalone DB but Watson appears to be doing 'more' that gets in my way.

Are we able to get this added, or as a fallback (even betteR) can the author comment in this issue on how I can achieve this potentially with Watson?

**Comment by jeffes** [comment]
Hm, maybe I can make a new field index and then hand parse the URLs going in and feed them into that index by themselves, would that work or am I talking out my ass?

**Comment by etianen** [comment]
I'd register with a custom search adapter:

https://github.com/etianen/django-watson/wiki/registering-models#tweaking-search-weighting

You can then customise how the fields you want to search are processed
before being stored in the db.

**Comment by jeffes** [comment]
Thanks, I'll give this a better try. I poked at it a bit before but didn't seem to get anywhere. Good to know that's the expected direction so I'll put in more time.
