### ISSUE TITLE
Clearing the database-cached data?

### ISSUE THREAD

**Issue by hellvix** [etianen/django-watson#167]
I have a platform where advertisements often get marked as "deleted" if they are not renewed. The problem is that they still appear registered on `watson`, leading to a 404 error. I believe, in my case, I  will have to rebuild the whole search table every time I update `watson`. Is there any command to clear the table, @etianen ? I want to use it before I run `build watson`.

**Comment by etianen** [comment]
If the advertisments are only marked as deleted, then you can filter these
out of your watson searches without having to rebuild the search data.

watson.register(YourModel.objects.filter(is_deleted=False))

See
https://github.com/etianen/django-watson/wiki/Registering-models#only-displaying-live-search-results

**Comment by hellvix** [comment]
Yeah, I do that. Somehow the results are still there. The build command returns the following:

17/06/2016 09:00:11 Deleted 0 stale search entry(s) in 'default' search engine.
17/06/2016 09:00:11 Deleted 0 stale search entry(s) in 'admin' search engine.
17/06/2016 09:00:11 Refreshed 1492 search entry(s) in 'admin' search engine.

Does it rebuild it from scratch or just adds new ones?

**Comment by etianen** [comment]
Are you using a bulk update to flip the flag? If so, don't, because that
will skip sending the post_save() signal that watson needs to keep it's
indices updated.

**Comment by hellvix** [comment]
Yeah, I have a crontab script that runs a django management command to bulk update my entries. However, I do update watson manually every now and then through crontab.

**Comment by etianen** [comment]
Hmm, actually, if you're
doing watson.register(YourModel.objects.filter(is_deleted=False)), then you
shouldn't need to run buildwatson to update the indices, since
the is_deleted filter is applied when the models are searched. It'll even
work with bulk updates.

What watson API call are you doing to get the search results with the
deleted models in?

**Comment by hellvix** [comment]
I use 

```
from watson import search as watson
search_result = watson.filter(Advertisement, query)
```

### apps.py
```
def ready(self):
        from housefy_app.models import Post
        from watson import search as watson
 
        advertisement = self.get_model('Advertisement')
        city = self.get_model('City')
 
        watson.register(advertisement.objects.filter(pub_status=Post.STATUS_PUBLISHED), fields=(
            "title",
            "type__name",
            "type__tags",
            "category__name",
            "category__tags",
            "city__name",
            "city__region",
            "city__tags",
        ))
 
        watson.register(city, fields=(
            "post_code",
            "name",
            "tags",
            "region",
        ))
```

**Comment by etianen** [comment]
Ah, yes, a bit of a gotcha there. The filtering you specify in the
register() doesn't apply to watson.filter(), only watson.search(). No good
reason for that, just legacy. It should really be fixed.

Meanwhile, you can get what you want with:

search_result = watson.filter(Advertisement, query).filter(deleted=False)

watson.filter() just returns a queryset of your model, so you can filter it
however you want. :)

**Comment by hellvix** [comment]
Humm, ok. In the documentation it says:

> watson.register(YourModel.objects.filter(is_published=True))
> 
> The above code will ensure that no models where is_published == False will appear in your search results.

I thought it would apply the filter and add the results to watson's search table.

**Comment by etianen** [comment]
I think I summed that up with "Ah, yes, a bit of a gotcha there. The
filtering you specify in the register() doesn't apply to watson.filter(),
only watson.search(). No good reason for that, just legacy. It should
really be fixed."

**Comment by hellvix** [comment]
:+1:

**Comment by etianen** [comment]
To be honest, django-watson needs a bit of love. I recently gave django-reversion a massive facelift, cleaning up 8 years worth of cruft and rewriting the docs. django-watson will get this treatment too, just as soon as I have the energy to contemplate it! :)

**Comment by hellvix** [comment]
Ok :-)
Den 17. jun. 2016 16.14 skrev "Dave Hall" <notifications@github.com>:
