### ISSUE TITLE
Watson ignore 'fields' when model is registering

### ISSUE THREAD

**Issue by ghost** [etianen/django-watson#170]
So, watson in my module working good. But when I add a new model to register, watson somehow ignore all arguments that I try to pass. My new model doesn't have any Text- or Charfield, only DateTime, Small Int and some Foreign Key. Well, I am expect from watson to not index this model at all, still, watson index all Foreign Key fields and DateTime fields too. It is little bit awkward, because other models (even with ManyToMany fields) indexing very well. I also tried to use `watson.filter(...)` with excluded models that connect via foreign key and i do not want to indexing them, but it really doesn't help me at all. Sorry if I do something wrong.

Django Version: 1.9.7
Watson Version: 1.2.2
Database: SQLite3

**Comment by etianen** [comment]
What code are you using to register your model?

If you're passing an empty tuple, then I believe it actually registers all
fields.

Why do you want to register a model with django-watson, but not register
any fields?!

**Comment by barsoo** [comment]
Here it is, **apps.py:**
```
from django.apps import AppConfig
from watson import search as watson

class DirectoryConfig(AppConfig):
    name = 'api'

    def ready(self):
        event = self.get_model('Event')
        watson.register(event, fields=('patient',))
```
where _patient_ is ForeignKey field. I even tried to pass exclude with all other model's fields and rebuild watson, but it index all stuff again

**Comment by etianen** [comment]
Hmm, so, the __unicode__/__str__ method of your model will also be indexed, in addition to any fields that you specify.

That might be causing the effect you're describing.

If you want to avoid indexing the __unicode__/__str__ method, you need to create a custom SearchAdapter, and override the `get_title()` method to return `""`.

https://github.com/etianen/django-watson/wiki/registering-models#tweaking-search-weighting

**Comment by barsoo** [comment]
Oh. It actualy was in the wiki. But I did not see it so many times. Anyway, custom SearchAdapter and overriding `get_title()` solve my problem. Now it is searching as I expect it to search. Many thanks.

**Comment by etianen** [comment]
No worries! The behaviour of indexing the __str__/__unicode__ method is
definitely a bit odd and unexpected when explicitly specifying fields to
watson.register().

At some point I'll attempt to improve the docs and API, but I don't have
time right now. :)
