### ISSUE TITLE
some unicode characters have been dropped

### ISSUE THREAD

**Issue by ratha-pkh** [etianen/django-watson#176]
Hi, I got an issue with watson when trying to search unicode.
eg.When I searched ផលិត, it turns out that watson removed to be ផលត. The problem is watson did removing character it thought non-word characters. Is there a workaround to fix this? Thanks.

```
RE_NON_WORD = re.compile(r"[^ \w\-\.']", re.UNICODE)

def escape_query(text):
    ...

    text = RE_NON_WORD.sub("", text)  # Remove non-word characters.
    return text
```

**Comment by etianen** [comment]
Try upgrading your django-watson. The latest version uses a much better regex.

https://github.com/etianen/django-watson/blob/master/src/watson/backends.py#L28
