### ISSUE TITLE
buildwatson command error

### ISSUE THREAD

**Issue by DBlackKat** [etianen/django-watson#177]
File "/Users/theblackcat/Documents/dev/website/restaurant_menu/myVENV/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 85, in handle
    if len(options['apps']):
KeyError: u'apps'

I was using Django 1.7.1 and kept having this problem, does watson support installing in virtual environment or I had register my models the wrong way?

**Comment by etianen** [comment]
What version of django-watson are you using?

**Comment by DBlackKat** [comment]
Is version 1.2.3

**Comment by etianen** [comment]
django-watson supports django 1.8 and higher. You can try using the older 1.2.2, which supports Django 1.7.

Even better, upgrade your Django! :)
