### ISSUE TITLE
PostgreSQL search for `-` and `+`

### ISSUE THREAD

**Issue by amureki** [etianen/django-watson#182]
Greetings @etianen 

Found that PostgreSQL that correctly works with `+` and `-` symbols in searching is not working in django-watson:
`RE_NON_WORD = re.compile(r'[:"(|)!><~*+-]', re.UNICODE)` which is used in `escape_query` escapes it before PG performs search.

Maybe we should have base `escape_query` and for every backend have inheritor of this method with correct backend symbols?

What do you think about this approach? If it is valid for you, I can make a PR with tests.

**Comment by etianen** [comment]
I'm not sure that django-watson should try to support boolean query
operators. Different databases have different capabilities, and there's
room for great error trying to abstract it.

If you want to use more advanced searches, I'd consider using the new
django postures-specific features directly.

**Comment by amureki** [comment]
@etianen nope, I not meant that these symbols should act as an operator. 
https://www.postgresql.org/docs/9.1/static/functions-textsearch.html doesn't show `+` and `-` there.

The thing is, for example: `test+test@example.com` is a valid email address and also valid search item for postgres ts_query.
But, because of `RE_NON_WORD` MySQL escaping (which should not apply to a postgres backend at all), search in django-watson is not working for that kind of values.

**Comment by etianen** [comment]
Ah, I see your point. I'd certainly consider a better per-database query
escaping a great pull request idea!
