### ISSUE TITLE
RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.

### ISSUE THREAD

**Issue by NotSqrt** [etianen/django-watson#194]
Hi,

The `search_results` and `search_result_item` template tags use the context to call `render_to_string`, which would prefer a dict instead of a RequestContext ...

It's possible to call `context.flatten()` to get a dict.

Thanks !

**Comment by etianen** [comment]
I'll take a pull request for this, or look into it myself when Django 1.11 lands.
