### ISSUE TITLE
Using Django-Watson to index non-database content 

### ISSUE THREAD

**Issue by engineervix** [etianen/django-watson#196]
In many cases, one needs to index flat (non-model-based) content on a website. For [Haystack](http://haystacksearch.org/), [Haystack Static Pages](https://github.com/pisapapiros/haystack-static-pages) provides this functionality. In addition, [Eric Holscher](http://ericholscher.com/about/) has [documented an alternative technique](http://ericholscher.com/blog/2010/nov/16/using-haystack-index-non-database-content/) which involves reading the file contents from the filesystem instead of from the database. 
**How can one index flat (non-model-based) content using Django-Watson?**

**Comment by etianen** [comment]
You need to register a custom `SearchAdapter`, as shown here:

https://github.com/etianen/django-watson/wiki/Registering-models#tweaking-search-weighting

The `get_content` implementation should return content loaded from the filesystem that is associated with the given model.

**Comment by engineervix** [comment]
Thanks @etianen I'll give it a shot.
