### ISSUE TITLE
ImportError: No module named 'watson'

### ISSUE THREAD

**Issue by tuxedojoe** [etianen/django-watson#199]
Hi, 
I like what I see about this project!

I'm trying to set up django-watson with Django 1.10.1, but I get: ImportError: No module named 'watson'
Am I wrong thinking it will work with Django 1.10:1 when I read its compitable with Django 1.8+?

Or am I doing something else wrong?

**Comment by etianen** [comment]
I don't think you've installed it correctly. That error implies that you've not installed it as a python module.

Did you follow the instructions here?:

https://github.com/etianen/django-watson/wiki

**Comment by tuxedojoe** [comment]
Thanks for such a quick response!
I did follow the instructions but after 3 below I get this error.

1) Install django-watson using pip: pip install django-watson.
2) Add 'watson' to your INSTALLED_APPS setting.
3) Update your Database:
Django >=1.7: Run the command manage.py migrate. 

-------

I did notice that while doing pip install django-watson it placed it in: /usr/local/lib/python2.7/dist-packages, which I seem is odd since I'm running python for 3.5. Tried to do the same and tried 'pip3 install django-watson', the files then got places in /usr/local/lib/python3.5/dist-packages but the error still occurred. 

Is there anything more I can try? Seems I'm stuck as I see it now.

**Comment by tuxedojoe** [comment]
Actually, it got solved by adding the PYTHONPATH to my venv/bin/activate file by adding this line:

export PYTHONPATH="/usr/local/lib/python3.5/dist-packages"

I thought that was handled automatically in the virtualenv but apparently not (or maybe I somehow got it erased): But all well and sound now. Hope this can help someone else too.

**Comment by etianen** [comment]
This should have been handled automatically by the virtualenv. I suspect
something is screwy in your dev environment.

Still, I'm glad you found a solution!
