### ISSUE TITLE
extra_context: How to use it?

### ISSUE THREAD

**Issue by ZaibiMughal** [etianen/django-watson#203]
Can i have a moment please. Actually what i am thinking is that i want to display a drop down list of values from my model. Right now it's not showing anything from my model, By reading your docs i think extra_context could help me out. If yes then please let me know the syntax to use it. Thanks

**Comment by etianen** [comment]
I don't think  yo need extra_context.

In your template code, do something like this:

``` html
{{search_result.obj.whatever_field_you_want}}
```

As in, you can access the original django model from `{{search_result.obj}}`.
