### ISSUE TITLE
Is there a global whitelist/blacklist of search terms?

### ISSUE THREAD

**Issue by ursomniac** [etianen/django-watson#204]
I've installed django-watson and am now getting tickets from the stakeholders that "term X isn't coming up, but term Y is...".

In the first case, the "term" they're looking for is 'JFK' (the initials - which does appear in the content in several places, in several objects).   I'm suspecting that django-watson filters out "short" words (which makes sense, generally), but it would be great if there is a way to have a "whitelist" of texts that will get indexed.   (I can foresee things like "DNA", etc. also being desirable search terms.)

**Comment by etianen** [comment]
django-watson delegates to the underlying database's full text seach
engine. So it's the database config where you have to look to customize
this sort of thing.

PostgreSQL, in general, has a better full text search implementation than
MySQL, but both allow a fair degree of customization.
