### ISSUE TITLE
"context must be a dict rather than RequestContext" with build in views

### ISSUE THREAD

**Issue by atabekm** [etianen/django-watson#209]
Hey,

Thanks for easy to use searching library for Django. I'm trying to show search results by using [build in views](https://github.com/etianen/django-watson/wiki/built-in-views), however getting:

> context must be a dict rather than RequestContext.

Django 1.11 and python 3.6 are used. Can you please advise on how to solve the problem? Thanks in advance.

**Comment by amureki** [comment]
@atabekm hey hey!
The fix to support Django 1.11 was merged to master, but not released to pypi yet.

Here is the discussion to follow: https://github.com/etianen/django-watson/issues/208

You always can install latest version right from github:
`pip install git+https://github.com/etianen/django-watson.git#egg=django-watson`

**Comment by atabekm** [comment]
Thanks @amureki.
I got from github, now it is working as expected.

**Comment by etianen** [comment]
I've just released 1.4.0, so there's no need to install from master now. :)

**Comment by atabekm** [comment]
Cool, thanks @etianen
