### ISSUE TITLE
KeyError at /dashboard/ u'query'

### ISSUE THREAD

**Issue by neeti25** [etianen/django-watson#210]
Where do i add this piece of code to render search results - {% search_results search_entry_list %}?
Also do i need to define the built-in search view in my app's views.py to get it working?

**Comment by etianen** [comment]
You need to add the built-in views to your urls.py:

https://github.com/etianen/django-watson/wiki/Built-in-views

You can then copy the watson/search_results.html template into your
template root and customize it.

**Comment by neeti25** [comment]
This is the traceback that i get:
[http://dpaste.com/3QBXXGH#wrap](url)
Here's my search form in header.html
`<html>
  <head></head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <form action="{% url 'watson:search' %}">
          <input type="text" name="q" value="{{request.GET.q}}" id="id_q">
          <input type="submit" value="Go">
        </form>
        <div class="navbar-header navbar-right">
          <p class="navbar-text">Signed in as {{user.first_name}}</p>
            <button type="button" class="btn btn-info navbar-btn">
              <a href="{% url 'mgmt:user_logout'%}">Logout</a>
            </button>
        </div>
      </div>
    </nav>
  </body>
</html>
`

And i haven't modified anything in search_results.html after pasting it in my app.
And i registered my models like this:
`class MgmtConfig(AppConfig):
    name = 'mgmt'
    def ready(self):
        User = self.get_model("User")
        watson.register(User)
        Student = self.get_model("Student")
        watson.register(Student)
        Teacher = self.get_model("Teacher")
        watson.register(Teacher)`

i don't understand the error exactly but it's somewhere in rendering the context of query string. Please help.

**Comment by etianen** [comment]
Your search form isn't in the email. Could you try again?

**Comment by neeti25** [comment]
Yeah.

![screenshot from 2017-07-07 16 53 16](https://user-images.githubusercontent.com/29422125/27955927-d081a384-6334-11e7-9407-0b44eda8df48.png)

**Comment by etianen** [comment]
Are you using the built-in views?

I'm confused, because the built-in views set the "query" context variable,
and your traceback indicates that the "query" context variable is not set.

Furthermore, your error seems to be in the base.html template, which has
nothing to do with django-watson.

**Comment by neeti25** [comment]
Yes, thank you. The error occured because i hadn't upgraded to the latest version of Django 1.3.1.
It works fine now.
