### ISSUE TITLE
Searching only in specified fields?

### ISSUE THREAD

**Issue by one-two-three-four** [etianen/django-watson#211]
What I have:
`watson.register(Hub, fields=("title", "text", "url", "meta",))`
What I do:
`watson.filter(Hub, query)`
But sometimes I would like to do:
`watson.filter(Hub.meta, query)`
to get Hubs with query in only meta.

Any way to achieve this using only Watson, without switching to lower-lever database-dependent search functions?

**Comment by one-two-three-four** [comment]
Found the perfect answer in here: #29 
https://gist.github.com/etianen/060d1fe02d79f9bc39b5

Should have searched better.

**Comment by etianen** [comment]
Glad you found a solution! :)
