### ISSUE TITLE
Search with special characters

### ISSUE THREAD

**Issue by amorino** [etianen/django-watson#215]
I'm having trouble searching for models with special characters on its properties. 

Ex. I'm searching for "something" and I'm expecting "sométhing, somethíng, something" in the results but I just get "something". Is this the expected behaviour? 

Thanks in advance!

**Comment by etianen** [comment]
That depends on your database backend. I've just added a wiki page
explaining your options:

https://github.com/etianen/django-watson/wiki/Language-support

**Comment by amorino** [comment]
Do I need to update the package?

**Comment by etianen** [comment]
Nope. Latest release is fine.

You will need to migrate watson to zero, then migrate it back again.
