### ISSUE TITLE
Django 1.7 support is broken in 1.4.1

### ISSUE THREAD

**Issue by Sovetnikov** [etianen/django-watson#216]
With RawSQL usage in 1.4.1 django-watson is not working with Django 1.7 anymore.

**Comment by carltongibson** [comment]
[Django 1.7 has been EOL for nearly two years now](https://www.djangoproject.com/download/#supported-versions). It no longer receives even security updates and is not safe to use in production. You should upgrade immediately.

**Comment by etianen** [comment]
I'm afraid that 1.7 is no longer supported by the main Django project, so
supporting it with django-watson isn't really something I'd like to commit
to.

Breaking 1.7 compatibility was an accident, but unless you can submit a
pull request with an easy fix I suspect it'll stay broken. django-watson is
tested against django 1.8+.
