### ISSUE TITLE
WATSON_BACKEND setting should be documented

### ISSUE THREAD

**Issue by barsch** [etianen/django-watson#218]
I was wondering about the countless ```SELECT version();``` queries in my SQL log. After a bit debugging and reading https://github.com/etianen/django-watson/blob/master/watson/backends.py I added

```WATSON_BACKEND = "watson.backends.PostgresSearchBackend"``` 

to my settings.py and those entries disappeared.

**Comment by etianen** [comment]
Are those entries a problem? It only occurs once on Django startup.

**Comment by barsch** [comment]
they actually show up every query which uses watson - is backend caching disabled with ```DEBUG=True```?

**Comment by etianen** [comment]
Okay, that's a bug. I've pushed a bugfix 1.4.2 release. It should be much
more efficient to use the adaptive search backend.

I've also documented the setting here:
https://github.com/etianen/django-watson/wiki/Database-support

**Comment by barsch** [comment]
awesome - thanks for the quick fix!
