### ISSUE TITLE
Register Filtered Queryset

### ISSUE THREAD

**Issue by zuzanatoldyova** [etianen/django-watson#221]
HI, thank you for a great plugin, I have one issue where it's not working quite as expected.
I'm trying to register a filtered queryset according to this [documentation](https://github.com/etianen/django-watson/wiki/registering-models#only-displaying-live-search-results), however it seems like the filter is not working because I get registered all my model instances. I tried it with specific fields and also without fields, run the buildwatson but I still get the same result.

**Comment by etianen** [comment]
Can I see the relevant code?

**Comment by zuzanatoldyova** [comment]
I found out that it's working with the search as described. I was confused because I was using filter.
