### ISSUE TITLE
filter not working with UUIDField

### ISSUE THREAD

**Issue by OskarPersson** [etianen/django-watson#227]
`watson.filter()` doesn't seem to work when the primary key is a [`Django.UUIDField`](https://docs.djangoproject.com/en/1.11/ref/models/fields/#uuidfield). I always get an empty result set. The data is indexed in the databse and `watson.search()` seems to work as expected.

I have setup a simple test project that demonstrates this [here](https://github.com/OskarPersson/wat). I've tested it with Django 1.11.6 in Python 2.7.14 running on macOS with SQLite 3.19.3 and MySQL Ver 14.14 Distrib 5.7.20 (using [mysqlclient 1.3.10](https://pypi.python.org/pypi/mysqlclient)).

```
>>> from books.models import Book
>>> from watson import search as watson
>>>
>>> Book.objects.create(title="My book")
<Book: Book object>
>>> watson.search('book')
<QuerySet [<SearchEntry: Book object>]>
>>> isinstance(watson.search('book')[0].object, Book)
True
>>> watson.filter(Book, 'book')
<QuerySet []>
```

**Comment by etianen** [comment]
Fixed in master. Let me know if it works for you!

**Comment by OskarPersson** [comment]
Works great, thanks!

**Comment by etianen** [comment]
Nice. I'll release next Monday.
