### ISSUE TITLE
returning matched sentences

### ISSUE THREAD

**Issue by AnonymousNoob** [etianen/django-watson#233]
Is there a way to return the matched phrases in a model field, example , qurey="hot dog" , search result includes queryset and "I had a hot dog yesterday" along with the query set ??

**Comment by etianen** [comment]
No, you'll have to do this logic in your own Python code by looking at the
text in the SearchEntry model, and finding the appropriate snippet.

Postgres has a native function to do just this, but because django-watson
aims to be database-agnostic, it doesn't provide any wrapper for using this.
