### ISSUE TITLE
How to get list of queries made?

### ISSUE THREAD

**Issue by Pulkit-Sharma** [etianen/django-watson#240]
Is it possible to retrieve the list of queries searched? I am using this on my project and love the results it shows.
I want to show list of popular searches. Is it possible to retrieve?

Please add a label for suggestion.

**Comment by etianen** [comment]
You can implement this entirely in your own codebase.

Whenever a user makes a query, write an entry in a database table
somewhere, keeping a tally. Or use redis and do something similar. The
possibilities are endless!

**Comment by Pulkit-Sharma** [comment]
Thank for reply. That was obvious, but thought if anything inbuilt was possible.
