### ISSUE TITLE
Which field the result comes from?

### ISSUE THREAD

**Issue by lucasradix** [etianen/django-watson#241]
I have a model with three textFields: title, description and sideText. 
One of the objects of this model is filled as:
title = 'Hello'
description = 'Hello everybody'
sideText = 'Welcome'

When I search for 'Hello', my result array has only one object with the 'content' attribute containing 'Hello Hello Everybody' (concatenation of title + description'). How can I get which model fields 'Hello' was found? That is, is there an array attribute, or something like this, in the result object containing 'title' and 'description'?

Thank you.

**Comment by etianen** [comment]
You cannot get which fields the match was found in. The searchable text is
concatenated by watson and put in a large full text index for efficient
search. This means that the informatino you're after is lost.
