### ISSUE TITLE
Not "live" search results still appearing in index

### ISSUE THREAD

**Issue by ianfitzpatrick** [etianen/django-watson#244]
When registering my User model for search indexing like this:

```
        watson.register(
            User.objects.filter(is_active=True),
            CaseInsensitiveSearchAdapter,
            fields=(
                'first_name',
                'last_name',
                'username'
            )
        )
```

I am still seeing Users with is_active=False in my search index. Again sorry I don't have a good repro for this, I have dropped all data in the table and run `manage.py buildwatson` multiple times (also tried User.objects.exclude(is_active=False) and a few other things) but users always show up in index.

Any idea what might be causing this? My backend is MySQL.

**Comment by etianen** [comment]
Registering a filtered queryset with django-watson will only affect results
returned by watson.search().

If you're using watson.filter(), you need to pass the same filtered
queryset in:

watson.filter(User.objects.filter(is_active=True))

I realise the docs could be clearer about this.
