### ISSUE TITLE
Can't search char field that contains a number or IP address.

### ISSUE THREAD

**Issue by aaronweaver** [etianen/django-watson#246]
**Using: 1.5.2**

When I update a field or try to search for an existing field that contains a number such as 127 or 127.0.0.1 I don't get any results. The backend is mysql. Would there be any setting that would cause that? Is there anyway to view the underlying query?

**Example:**
clean_query = "127.0.0.1"
endpoints = watson.search(clean_query, models=(Endpoint,))

**Model:**
host = models.CharField(null=True, blank=True, max_length=500,
help_text="The host name or IP address, you can also include the port number. For example" "'127.0.0.1', '127.0.0.1:8080', 'localhost', 'yourdomain.com'.")

**Comment by etianen** [comment]
Check out the MySQL setting "ft_min_word_len". I think you might want to
set it to 2 or 3, so it doens't ignore short numbers.

**Comment by frnhr** [comment]
Seems to be more complicated with Postgres :(
