### ISSUE TITLE
5 GB database buildwatson command took hour and end with fatal error

### ISSUE THREAD

**Issue by Pulkit-Sharma** [etianen/django-watson#247]
I am trying to index a table with 3 million rows.
When I run manage.py buildwatson, it takes around one hour and then without any data creation it ends with error "DB under recovery".
Its a postgres DB with 64GB RAM and 16CPU. CPU usage stays around 15% through out.

What could be the issues? Buildwatson is made for small datasets?

**Comment by etianen** [comment]
Try running buildwatson with the --non-atomic flag.

It'll still take a long time to run, but your transaction won't overflow
and explode.
