### ISSUE TITLE
Per user or profile results

### ISSUE THREAD

**Issue by n3storm** [etianen/django-watson#253]
I need to index and search a lot of documents. Documents are used by different organizations than can only access a subset of the whole lot.

Access is determined by groups in a tree like structure. Tree is finite.

Is it crazy or dumb or impossible the following?:

Create a proxy model per tree node to filter documents accordingly to access permission and register to django-watson those proxy models.

Thanks in advance and any other approach that doesnt't include "filtering on view" will be welcomed.

**Comment by etianen** [comment]
Creating a proxy model per tree node sounds pretty crazy, IMO.

I would almost certainly advocate filtering the search result queryset on
view to apply the permissions there.

**Comment by n3storm** [comment]
There where less than 120 proxies (done programatically of course).

You are probably are right but I found this solution for Django Haystak:
https://stackoverflow.com/questions/28561054/django-haystack-create-multiple-indexes-for-the-same-model

How about to make 17 proxies? only for one level and second level fathers? and then filter from there on the view. That will filter out a lot and queries will be much smaller. Those 17 will not grow ever. Their children will grow with time (slowly).

**Comment by etianen** [comment]
I mean... maybe it would work...

But I don't see what's wrong with filtering on view. That just seems less
hacky to me.

**Comment by n3storm** [comment]
I realized there are roughly 18000 entries and would not duplicate within the next 5 years.

I will follow your advice @etianen, thank you very much :) and thank you for the KISS reminder ;)
