### ISSUE TITLE
An "s" character at the end of a word

### ISSUE THREAD

**Issue by roodie** [etianen/django-watson#256]
Interesting problem, I am using the PostgreSQL backend, with the following locale:

```python
WATSON_BACKEND = 'watson.backends.PostgresSearchBackend'
WATSON_POSTGRES_SEARCH_CONFIG = "pg_catalog.hungarian"
```

One of the fields contains my family name, which is "Farkas". Now for some reason in the index it gets truncated to 'farka'. 

Example:

```json
'farka':8 'istvan':7 'document':9
```
Now if I use watson.filter() to look for my family name, there are no results. 

I guess the problem is that initially I forgot to set the correct locale when I used 'installwatson' and the trigger is set to pg_catalog.english. Tried to use 'manage.py uninstallwatson' then reinstall it, but this failed. I was able to correct the functionality by deleting the table and migration and remigrating watson. Probably worths a note in the docs.

**Comment by etianen** [comment]
I suspect that `./manage.py migrate watson zero` followed by `./manage.py
migrate watson` would acheive the same effect for changing the postgres
search config. Can you confirm?

**Comment by roodie** [comment]
Yes, the "I was able to correct the functionality by deleting the table and migration and remigrating watson" part means exatly that, sorry for the vague wording  :-)

**Comment by etianen** [comment]
Great! I've added a note at the bottom of the wiki page:

https://github.com/etianen/django-watson/wiki/Language-support
