### ISSUE TITLE
./manage.py buildwatson extremely slow on 0,5 million rows

### ISSUE THREAD

**Issue by clime** [etianen/django-watson#26]
In my Postgresql db, there are around 438 972 rows that should be tracked by watson. The problem is that full index build (using the buildwatson management command) is extremely slow.

```
(cb)clime@vm6879 /srv/www/cb $ time ./manage.py buildwatson

Killed

real    123m22.753s
```

Here the process was killed probably because it reached some system limits. It had been running for more than two hours and didn't finish.

These are register commands I use:

```
  watson.register(Crag, fields=('normalized_name', 'country'))
  watson.register(Member.objects.all(), fields=('normalized_name', 'user', 'country'))
  watson.register(Event, fields=('normalized_name', 'country'))
  watson.register(Route, fields=('normalized_name', 'crag__name', 'crag__normalized_name'))
```

The majority of all objects is contained in the Route model (more than 400 000). 

I would be very happy if the time could be reduced somehow.

**Comment by joemarct** [comment]
@clime, would you mind to share the PL/pgSQL script you made? i have a similarly sized database that i need to build an index from.
