### ISSUE TITLE
Some search terms seem to be ignored

### ISSUE THREAD

**Issue by jmb** [etianen/django-watson#262]
I have got watson set up for my project, however sometimes it fails to give me any results when I think it should. For example:
 
```
>>> watson.search("lie")
<QuerySet []>
>>> watson.search("det")
<QuerySet [<SearchEntry: 1:29:15 The 7 Card Lie Detector>, <SearchEntry: 1:53:25 The 7 Card Lie Detector>, <SearchEntry: 2:07:25 Question: Clarification on spelling of suits for The 7 Card Lie Detector>]>
>>>
>>> watson.search("Across")
<QuerySet []>
>>> watson.search("awesome")
<QuerySet [<SearchEntry: 0:25:25 2.	Basic Coins Across - A simple but awesome traveling coins effect>]>
>>> watson.search("awesome").first().content
'2.\tBasic Coins Across - A simple but awesome traveling coins effect'
>>> watson.search("awesome").first().title
'0:25:25 2.\tBasic Coins Across - A simple but awesome traveling coins effect'
>>> watson.search("awesome").first().description
''
```

Can anyone shed any light on why would this happen?

**Comment by jmb** [comment]
I should add that I am using MySQL as my database.

**Comment by etianen** [comment]
No idea, sorry. If you can identify an issue, I'll take an MR.

**Comment by jmb** [comment]
Thanks. I've found the SQL in your code and am trying it directly...
`SELECT * FROM watson_searchentry WHERE MATCH (title, description, content) AGAINST ('across' IN BOOLEAN MODE);`
...the same issues arise, so it's obviously a MySQL issue. Weird!

**Comment by jmb** [comment]
Ahah, I've found the issues. The default minimum word length is 4 and there is a list of "stop words": https://dev.mysql.com/doc/refman/5.5/en/fulltext-stopwords.html
