### ISSUE TITLE
Document SearchContextMiddleware

### ISSUE THREAD

**Issue by valentijnscholten** [etianen/django-watson#268]
By accident I found the `SearchContextMiddleware` which I think can be used to have more efficient model updates, especially when some model instances are updated multiple times during a single reuquest.

Is this correct? Might be useful to document this (can be short)/

I updated the Wiki page: https://github.com/etianen/django-watson/wiki

Didn't know I had write access, was expecting the usual github prompt to create a branch/PR there :-)

**Comment by etianen** [comment]
It's just using the default settings, which I guess is public write? Who
knew?!

Thanks for the update, and for letting me know.
