### ISSUE TITLE
Search engine can't find small words

### ISSUE THREAD

**Issue by marcelosalloum** [etianen/django-watson#27]
Hello guys,

First of all, congratulations for this amazing tool, it really surprised me, thanks =)

It seems to me that among my models fields, watson can only find words that have 4 or more letters. Is that a filter anywhere that does not indexes the 3-letters-or-less words?

For example, in my MySQL there is a field containing the name 'catherine shu'. When I search for Catherine it returns the results correctly but when I search for 'shu', it does not return anything. Is that a way to specify a thorough kind of search?

Cheers

**Comment by mahiti-py** [comment]
Thanks a lot....

It did not work for me when I add at last line : ft_min_word_len = 2

I added at below basic settings.


Works fine..

Thanks a lot mam .:)
