### ISSUE TITLE
Mention in the docs that watson does not work with bulk_create

### ISSUE THREAD

**Issue by bcye** [etianen/django-watson#272]
As far as I know, watson's automatic updating of the index does not work when using bulk_create, as signals are not fired in that case. It would be good to add this to the docs.

**Comment by etianen** [comment]
It's mentioned here: https://github.com/etianen/django-watson/wiki/Registering-models#manually-updating-the-search-indexes

Surfacing this sort of information is difficult. The larger the docs, the harder it is to find things. Really, django-watson should use readthedocs for a nicer interface.

**Comment by bcye** [comment]
I missed that, even though I read the section twice :/
