### ISSUE TITLE
Error after updating django to latest version

### ISSUE THREAD

**Issue by Pulkit-Sharma** [etianen/django-watson#281]
I have updated the django to latest version and even upgraded postgres from 9.6 to latest version 12. After upgrading getting this issue with watson.

Exception Type: | IntegrityError
-- | --
null value in column "search_tsv" violates not-null constraint

Exception Location: | /usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py, line 84, in _execute
-- | --
/usr/bin/python3
3.8.5
['/home/django_project',  '/usr/local/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/dist-packages',  '/usr/lib/python3/dist-packages']
Sun, 07 Mar 2021 22:41:35 +0530

I am adding a post to database, watson is throwing this error.

**Comment by Pulkit-Sharma** [comment]
@etianen please help. The error is on live website.

**Comment by etianen** [comment]
Can I have the full traceback?

**Comment by Pulkit-Sharma** [comment]
The issue was with upgrading Postgre 9.6  to Postgres 12. watson_searchentry index trigger files were not copied in upgraded version.
I droped watson_searchentry table and migrated again with watson. Copied old data manually.

Since it was on live site, did not do much debugging. 
Anyway thanks.
