### ISSUE TITLE
Issues with indexing with taggit

### ISSUE THREAD

**Issue by udit-001** [etianen/django-watson#299]
I am making use of [django-taggit](https://github.com/jazzband/django-taggit/) on my model, for eg:

```python
class Post(models.Model):
    title = models.CharField(max_length=255)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    tags = TaggableManager()
```

and I have the above registered to Watson like this:
```
watson.register(Post, fields=("title", "category", "tags")
```

Now, the index gets automatically updated to new include a new Post when I create one from the admin.
But when I try to perform a search:
- It works fine if put in a category name
- It gives zero results when I put the search keyword as one of the tags in the Post.

But when I manually go and update the index using the `buildwatson` command, it starts returning results for tag search. Is there a problem in my configuration causing this, or do I need to tweak the indexing to accommodate automatic indexing for the tags? 

Any suggestions would be appreciated!

**Comment by udit-001** [comment]
Adding the middleware did the trick, `watson.middleware.SearchContextMiddleware`. But I couldn't find any transaction middleware as mentioned in the wiki 🤔

**Comment by etianen** [comment]
Nice! I've updated the [wiki page](https://github.com/etianen/django-watson/wiki/Registering-models#searching-across-related-models) to mention the equivalent `ATOMIC_REQUESTS` setting.
