### ISSUE TITLE
Searching for non-model related items (like views)

### ISSUE THREAD

**Issue by gawry** [etianen/django-watson#305]
I was thinking about building a UI like the one in https://www.helpbar.ai/ so I could show both results from the models and some of the views like common actions from the application. 

Do you have an idea on how to mix those results? One solution I could think of would be actually creating a model for those app actions and index those together.

**Comment by etianen** [comment]
Yes, you'll need to mirror the app actions into a model to include it with the `django-watson` search, since the search is all backed by the database.
