### ISSUE TITLE
Django 1.7 does not recognize data migrations properly

### ISSUE THREAD

**Issue by JirkaV** [etianen/django-watson#79]
First, a warning - this may be related to my setup only. But sharing it anyway since it might affect someone else too.

My webapp uses django-nose for testing. As I was moving it to Django 1.7, I noticed that several of my tests were failing with error similar to this:
```
    return self.cursor.execute(sql, params)
ProgrammingError: column watson_searchentry.search_tsv does not exist
LINE 1: SELECT (ts_rank_cd(watson_searchentry.search_tsv, to_tsquery...
```

A bit of digging revealed that migrations for watson were not running properly. Django 1.7.1 was claiming that watson was an "unmigrated app" as it had old style  "South" migrations which were not being applied during my test run.

I did try to convert them to new format following Django migrations tutorial, but the migration involving "installwatson" was ignored.

I ended up resolving it by creating a new data migration for watson (using "python manage.py makemigration --empty watson" and updating the migration file so it looks like this:
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.core.management import call_command
from watson.registration import get_backend


def install_watson(apps, schema_editor):
    '''watson needs to be installed in the environment once DB is recreated
    (e.g. during tests). Django 1.7 didn't pick it up during conversion
    from south migrations to this is a workaround
    '''
    ## call_command("installwatson", verbosity=0)

    # the command above has problem with @atomic decorator, so we do it
    # manually


    backend = get_backend()
    if backend.requires_installation:
        backend.do_install()


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(install_watson),
    ]
```

Sharing it here just in case someone else runs into the same issue.

**Comment by JirkaV** [comment]
That fixed it for me too, thanks!

**Comment by codingjoe** [comment]
@etianen the new migration folder contains an `__init__.py`. That tells django to fake the migration. Therefore creating a django 1.7 installation from scratch is rather difficult.

**Comment by etianen** [comment]
I don’t understand. Could you clarify?

**Comment by codingjoe** [comment]
I thought it would be explicitly stated here, but it isn't. I might be mistaken, but it did fake my initial migration.
https://docs.djangoproject.com/en/1.7/topics/migrations/#upgrading-from-south

**Comment by etianen** [comment]
I believe that it fakes the initial migration if the tables already exist in the database. If they’re not in the database, then it does the initial migration as usual.

At least, that’s how all my other projects seem to be behaving?

**Comment by codingjoe** [comment]
This might just be it. I could have run the build command in advance. Never mind, thanks.

**Comment by iqbalhusen** [comment]
When I run `$ python manage.py makemigrations --empty watson`, it overrides the initial migration file, i.e. the `0001_initial.py` file. Can anyone please explain the steps to write the custom migration file?

**Comment by codingjoe** [comment]
@iqbalhusen why would you create a migration for yourself in a different app?
But regarding your question, it might do that, because the initial migration is in fact a "datamigration".
It just calls the management commands `installwatson` and `uninstallwatson`.
i don't know why it would recreate a migration tho, this smells like a django bug. You should investigate and report. There were a couple of bugs in v1.7 migrations.
You might also want to retry with the current django master, your problem might already be fixed.

**Comment by etianen** [comment]
The first migration isn’t just a data migration, it also sets up the SearchEntry table.

I’m also a bit confused as to why @iqbalhusen would be doing this. I’d also second the “django bug” hypothesis.

**Comment by iqbalhusen** [comment]
I was just following the first comment to fix this issue (comment by @JirkaV ). Anyways, I solved it by using the latest master branch of the `django-watson` since it contains the django 1.7 migrations. The pip version doesn't contain a django 1.7 migration and contains only south migration.

**Comment by codingjoe** [comment]
@iqbalhusen you cold just install it and run the command. You don't really need the migration. It's just nice to have.
