### ISSUE TITLE
Building the index from scratch takes a while

### ISSUE THREAD

**Issue by thedrow** [etianen/django-watson#85]
170000 records took about an hour to build.
Can we parallelize some of the work so that for example each model will use a different process to build it's index?
We could use the ProcessPoolExecutor if it's available.
What do you think?

**Comment by etianen** [comment]
This feels very much like one of those tasks that can only be performed with any real efficiency on the DB server. Unfortunately, the configuration for django-watson is all Python-side, in the form of SearchAdapter classes. This means that all the data needs to be streamed through Python.

There is some indication that the postgres machine doesn’t handle the bulk inserts in a performant manner, and could benefit from multiple simulataneous connections. Discussion here:

https://github.com/etianen/django-watson/issues/51

The worker pool approach described in the last comment hasn’t been attempted. If you could find a way to leverage it in a patched buildwatson command that noticeably improves performance, I’d love to see the result.

**Comment by thedrow** [comment]
I'll give it a go later.
Would it be ok if futures would be added as a dependency for Python < 3.3?

**Comment by etianen** [comment]
I'd rather avoid the dependency, if possible. If have thought the correct architecture for this would be a main thread that reads rows from the DB and sends them down a queue in large batches to a worker pool of threads. The workers consume rows batches, write the index models to the db as one bulk insert, then mark the task as done in the queue. The main thread then joins the queue before exiting.

**Comment by thedrow** [comment]
Threads do not allow (real) parallel processing in Python. Only parallel I/O.
You can use a process pool instead. I suggested futures because it's much simpler then managing a pool of processes by yourself.

**Comment by etianen** [comment]
You’d correct in that threads do not allow parallel execution (usually). However, it’s parallel IO we’re looking to achieve here. The analysis performed in a past issue was that:

a) Python is IO bound.
b) Postgres is CPU bound for a single connection.

That is, Postgres creates a process per connection, and that process is CPU bound, which leads to Python being IO bound. Communication between Python threads is faster than communication between Python processes, and will achieve the goal of multiple parallel postgres connections.

**Comment by thedrow** [comment]
But Django doesn't pool connections anyway so using threads will not help unless the user uses a pool.

**Comment by etianen** [comment]
Each thread gets it’s own connection, and will keep that connection open for all inserts. So a thread pool is also a connection pool.

**Comment by thedrow** [comment]
Are you sure about that? Because I'm pretty sure that unless you use something like https://github.com/kennethreitz/django-postgrespool you don't get a connection per thread.

**Comment by etianen** [comment]
Here you go:

https://github.com/django/django/blob/master/django/db/utils.py#L144

The cached connections are thread-local.

Whilst the postgres connections can be shared between threads, other DB engines don’t behave so well. Django’s approach is cautious, with a connection per thread.

**Comment by thedrow** [comment]
I'll give it a shot :)

**Comment by thedrow** [comment]
After some research it seems that dropping the indexes and recreating them [concurrently](http://www.postgresql.org/docs/9.3/static/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY) after buildwatson is finished speeds things up on the database side.
I'm still researching what can be done about the trigger which causes exclusive locks to be aquired on the ```watson_searchentry``` table.

**Comment by thedrow** [comment]
Postgres is not I/O bound but CPU bound.
[It uses one process per connection] so using multiple connections like we suggested will speed up the building of the index.

**Comment by etianen** [comment]
Probably.

I recently had to optimise a massive database migration for an internal project. Rather like this problem, it consisted of streaming all the data out of postgres, through a python process, and back into postgres via a very large number of updates. The dataset was 1.8TB.

Looking at the process list, it seemed that postgres was stuck at 40% CPU, and Django was stuck at 60% CPU. That is, the two processes appeared to be stuck in lockstep, both CPU bound.

I tried the following approaches to speed this up:

1. A single python process reads the data, then farms it out to four worker processes, which then process it and stream it back into postgres over their own four database connections. Performance improvement - none!

2. Re-writing the Python processing code in a Postgres stored procedure, to avoid the overhead of streaming it to Python. Running the Performance improvement - down by 30%! (plpgsql is too slow to efficiently do the processing, despite saving bandwidth streaming to python).

3. Micro-Optimising the python code that processed the data. Performance improvement - up by 30%. (The processing involved converting to a compressed binary format, so using numpy really helped here).

4. Performing limited database-side aggregation to reduce the bandwidth required to stream the data to Python. Performance improvement - up by 100%!

5. Using bare-metal postgres database cursors and gnarly generator functions to stream the output of one cursor through the processing routine into another cursor’s execute_many() function. Performance improvement - up by 20%!

6. Running the same code on an SSD-powered server. Performance improvement - up by 1000%!

7. Running the same code having first dropped all possible indexes, then recreating them after - No performance improvement.

The important thing to note here is that parallelism didn’t help a damn. The major cause of slowdown was hard drive access by postgres, and a single postgres connection could easily max out the hard drive, even on an SSD. The next major cause of slowdown was bandwidth between python and postgres. The next major cause was inefficiencies in the python code.

So, while I’m expecting that buildwatson can be optimised further, I suspect that it’ll take a lot of trial and error to pin down exactly where the slowdown is, and it’s probably not where we initially think it is.

**Comment by thedrow** [comment]
I'm going to let my DBA review this since he's the expert.

**Comment by thedrow** [comment]
We've hit this again and a query that is specific to our needs took under 2 minutes to rebuild the entire index.
I think we need to change the search adapter design to return F objects instead of values.
That will allow you to write a generic query that updates everything at once.

**Comment by etianen** [comment]
I’m afraid I’m not entirely sure what you mean here.

**Comment by thedrow** [comment]
```SQL
UPDATE
	"watson_searchentry" 

SET
	"engine_slug" = 'default',
	"meta_encoded" = '{}',
	"description" = concat_ws(' ',first_name::text,last_name::text,middle_name::text),
	"title" = users_user.email,
	"url" = '',
	"content" = concat_ws(' ',first_name::text,last_name::text,middle_name::text,replace(replace(email::text,'@',' '),'.',' ')),
	"search_tsv" = setweight(to_tsvector('public.english_nostop', coalesce(users_user.email, '')), 'A') ||
                    setweight(to_tsvector('public.english_nostop', coalesce(concat_ws(' ',first_name::text,last_name::text,middle_name::text), '')), 'C') ||
                    setweight(to_tsvector('public.english_nostop', coalesce(concat_ws(' ',first_name::text,last_name::text,middle_name::text,replace(replace(email::text,'@',' '),'.',' ')), '')), 'D')

from users_user 

WHERE
"watson_searchentry"."object_id" = users_user.object_id and
	"watson_searchentry"."engine_slug" = 'default' AND
	"watson_searchentry"."content_type_id" = 15;
```

This query rebuilds the index under two minutes.
In order to be able to do something like that, that generates dynamically you need to use F() objects that reference the fields you're using e.g.:
```python
class NewSearchAdapter(SearchAdapter):
  def get_title():
    return F('email')
  def get_description():
    return CONCAT(F('first_name'), F('last_name'))
```
and then you can build a query from those that will set the search_tsv and the fields correctly.

**Comment by etianen** [comment]
A F() won’t be good enough, since the database queries are already using raw SQL, so complex Django ORM abstractions won’t work.

It also won’t support custom search adapters, since these use Python code to process the field content.

Making this approach work in a cross-db manner, while remaining backwards compatible, feels like an impossible task.
