### ISSUE TITLE
watson.register not working 

### ISSUE THREAD

**Issue by audioburn** [etianen/django-watson#91]
did watson.register(MyModel) in AppConfig.ready(), watson.search('search term') returned an empty list.

did watson.register(MyModel) in models.py, watson.search('search term') returned an empty list.

did watson.register(MyModel) in shell, watson.search('search term') returned an empty list.

MyModel is filled will models. These models have CharFields and TextFields.

I'm running Django 1.7 and followed all the instructions for installation, I can see watson_searchentry in my postgresql database. To be clear, I did both manage.py installwatson and manage.py buildwatson. I did manage.py makemigrations, manage.py makemigrations watson (created 0001_initial.py), manage.py migrate (no migrations), manage.py migrate watson (no migrations). 

watson is in my INSTALLED_APPS. 

Here is some code: 

    #apps.py

    from django.apps import AppConfig
    import watson

    class LinksAppConfig(AppConfig):
        name = 'links'
	    def ready(self):
              Link = self.get_model('Link')
              watson.register(Link)

    #shell 
    in   >> import watson
    in   >> watson.search('charlie')
    out >> []

Link has some models with the name 'charlie' in them.

Please help

**Comment by etianen** [comment]
Are there any rows in watson_searchentry?

**Comment by audioburn** [comment]
Woah that was quick. No sir

**Comment by etianen** [comment]
Can you try putting a print statement after watson.register(), to see if that code is actually be executed?

**Comment by audioburn** [comment]
I'm getting "None"s when I do this in shell: 

    import watson
    from links.models import Link
   
    print watson.register(Link)

though, when I do

    Link.objects.all()

all the objects in Link are returned

**Comment by etianen** [comment]
No, I mean, in your code, put a print “foo” or something immediately after your register call. That’s to ensure that the register code is actually being run by Django at startup.

**Comment by audioburn** [comment]
Ah ok

My code: 

    #apps.py

   from django.apps import AppConfig
import watson

class LinksAppConfig(AppConfig):
	name = 'links'
	def ready(self):
		
		Link = self.get_model('Link')
		watson.register(Link)
		print 'foo'

		User = self.get_model('UserProfile')
		watson.register(User)
		print 'bar'

		Comment = self.get_model('Comment')
		watson.register(Comment)
		print 'baz'

I did get 

'foo'
'bar'
'baz'

**Comment by etianen** [comment]
And the output from ./manage.py buildwatson with those print statements in place?

**Comment by audioburn** [comment]
Hey, sorry, edited the previous comment, which contains the traceback

**Comment by etianen** [comment]
It looks like the get_absolute_url method of one of more models is throwing an error.

**Comment by audioburn** [comment]
I flushed my db and buildwatson ran without errors. Going to add some rows and report back later

**Comment by audioburn** [comment]
It works now! Looks like the error was on my side. Sorry about that. Thanks a lot for the help!

**Comment by etianen** [comment]
No worries! Phew!

**Comment by thedrow** [comment]
Care to close as won't fix?
