### ISSUE TITLE
Watson does not search russian words.

### ISSUE THREAD

**Issue by astrikov-d** [etianen/django-watson#93]
Hi. I'm using PostgreSQL as the database and Django-watson does not search russian words. This is because `search_config` property in the `PostgresSearchBackend` class is set to "pg_catalog.english" and there is no way to change it via configuration :( 
By default, full text search in PostgreSQL use the default language of db scheme  and automatically recognize the language of search term.

**Comment by etianen** [comment]
You can subclass the PostgresSearchBackend and set search_config to your language of choice.

https://github.com/etianen/django-watson/blob/master/src/watson/backends.py#L160

Then set WATSON_BACKEND = “path.to.your.SearchBackend”, and you should be good to go. (You’ll also need to delete and recreate the watson_searchentry table.)
