### ISSUE TITLE
Support for django-polymorphic

### ISSUE THREAD

**Issue by NotSqrt** [etianen/django-watson#97]
It would be great if https://github.com/chrisglass/django_polymorphic were supported out of the box.

Basically, django_polymorphic is just a way to subclass models to obtain specific behaviour.
The important part for watson is that it uses multiple content type ids.

The bug I got is that ``search_result.object`` can be ``None`` for these polymorphic models.

I circumvented it by creating a copy of the templatetag search_result_item :

```python

from django.contrib.contenttypes.models import ContentType

@register.simple_tag(takes_context=True)
def search_result_polymorphic_item(context, search_result):
    obj = search_result.object

    # added code
    if not obj:
        obj = ContentType.objects.get(
            id=search_result.content_type_id
        ).model_class().objects.get(
            id=search_result.object_id
        )
    # end added code

    params = {
        "app_label": obj._meta.app_label,
        "model_name": obj.__class__.__name__.lower(),
    }
    # Render the template.
    context.push()
    try:
        context.update({
            "obj": obj,
            "result": search_result,
            "query": context["query"],
        })
        return template.loader.render_to_string((
            "watson/includes/search_result_{app_label}_{model_name}.html".format(**params),
            "watson/includes/search_result_{app_label}.html".format(**params),
            "watson/includes/search_result_item.html",
        ), context)
    finally:
        context.pop()
```

But Django has to execute additional SQL queries.

It would be better if the ``content_type_id``  was correct in the first place.
It's probably just a matter of using ``ContentType.objects.get_for_model(model, for_concrete_model=False)`` at proper places.

**Comment by etianen** [comment]
This does sound like django-polymorphic is breaking Django’s own prefetch_related. My instinct would be to look to correct this breakage in django-polymorphic itself, rather than put a hack into django-watson.

That is, unless a nice elegant hack can be put together that doesn’t really add to the code complexity significantly. Or, even better, a general-purpose solution that doesn’t qualify as a hack!

I’ll take any likely-looking pull-request with tests. :P

**Comment by JanMalte** [comment]
Is this issue closed without a solution?
Or are polymorphic models supported in a new release?

**Comment by etianen** [comment]
I believe that this is caused by a bug in django's prefetch-related, or django-polymorphic. Some things seem to trigger it, but there's not a lot django-watson can do.

As a workaround, use the template tag posted by @NotSqrt.
